[package]
name = "Phobri64_GUI"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.20.1"
egui = "0.20.1"
hidapi = "2.1.0"
tracing-subscriber = "0.3.16"
